trailer-demo
andrii248/project7 pull request #79
Opened 2022-06-19 21:06 UTC by GudymaVit

поки так, не все відкривається, трішки загруз так як думав поки не виходить, зараз по Лєненій фунції , в консолі  є помелки,

2022-06-19 21:26 UTC, shmetanelena requested changes

2022-06-19 21:26 UTC, shmetanelena commented on src/js/tmdb.js
> +    return `https://www.youtube.com/embed/${item.key}`;
Принимаю, согласна с добавлением /embed

2022-06-20 04:37 UTC, andrii248 commented on src/js/tmdb.js
> +    return `https://www.youtube.com/embed/${item.key}`;
супер

2022-06-20 04:39 UTC, andrii248 approved these changes

2022-06-20 04:45 UTC, andrii248 approved these changes

2022-06-20 04:58 UTC, merged